### ISSUE TITLE
Sample update

### ISSUE THREAD

**Issue by chipzoller** [kyverno/sample-extension-service#2]
Sample needs to be updated according to latest schema changes

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-namespaces      
spec:
  validationFailureAction: Enforce
  rules:
  - name: call-extension
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
    context:
    - name: result
      apiCall:
        method: POST
        data:
        - key: namespace
          value: "{{request.namespace}}"
        service:
          url: http://sample.kyverno-extension/check-namespace
          caBundle: |-
            -----BEGIN CERTIFICATE-----
            <snip>
            -----END CERTIFICATE-----            
    validate:
      message: "namespace {{request.namespace}} is not allowed"
      deny:
        conditions:
          all:
          - key: "{{ result.allowed }}"
            operator: Equals
            value: false
```
